[google]
type = "service_account"
project_id = "facebook-scrapper-456519"
private_key_id = "14df01e045575cfb304a6794c2be212f46d0e893"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8ugYPQUt18Sih
HF8juqBkQqkkygx/jT00+ACqGOMixxBFNUNXYLLzgZcKKFm8GdqoHDQTzwaLgPzo
GeoHV8XF+/P30p9y+CJGmiOSjR2o/NOcZNxRZ2SynIC68DYgxwp2QKWeXzY5QHIb
8Phts8kZfWEiXK8fU7rVtup0om9QVBoUyA2bs5s6cNaV56cXMotMjo/7XDbO2g3R
m3LA2arDKw9fPlwORjfT2ODChCSFOcxbDJU0emM3rN78HXea+afV99oVnaI6EZcI
ISLrQwmzBYWEdtFr3k6ph/EGhDJ2LAWbLulhEwknRYtktLhemd0DIBl5CNKIo3h2
nJqCSc+hAgMBAAECggEACFxnwScX+CiVWkvhkCQ9ZQEKBsyiZfKPKV3/rjQjjep1
Qfz/LStmH4EYfKqhzRefzFj8L/t46Kxv0pA2rMQantqPv0/YC2B1qPHnt7SjltVl
QkAP/arqYbpVaVK+hyW3mi+41qMVCc9yhA02fapcc1IOwAEMq23gG1s67ay2Peqk
amonyLuqFxZ2nYxewY93/cb0b4kICSdhOYG2wli7EsZyaNq0YInPqC7XRcGxJc60
JJKTV7KXO+B5nUrLJSHBEPkLcFNM3ikaoYyx2kW5WuuHRHmW7QwbZ5qanNv/qp95
OfY4up+p0thnYhEDbop4KODgBc1UjdPawwqfmyHHpQKBgQDojiEj5S3+DmCK/4po
BdoBrAQfudJcep8bPrb4yUpDaO/oHhpkxpHqTucsIHKb9Wr8m72yViKFJ8mCJj4d
eLcJSS8BJ8U6/WTkt7Kj4nvTtMog/DYZhSbCc6sRlVCgp9wHM+Nm7dkWCwlPUcEE
RkLy/cOiEh8jnW+pVPfDsiorXQKBgQDPwMBGNTcEUYZRTYVQ02ojVzN9UE2Hk/bJ
YMtPLR5BuXwCc+zB2TcvKqf/bHhshAkJ7l9rKIf4phXbR6beZ92/cKuCM4vWmCXt
6YkcWceHwoj/NSftwUFz8csShsHLyG/LBQZHGhnwxeFS66iPH8qZot66KXZrH2TA
WYhzDaI1FQKBgQCjBQccN4qvHnr01T+7veZd56yYZNWe+GJSYfs3mTtS19vdFkUg
QcaFvrv0xeYxh69w1uf6fMEEIKj0cER4umdsvf2STMPIn1q7rj4u/hQZixFqYAK4
jwtlolnYIJh9lk36SphtTewwtJnZHZE1ot9JoTQjh5qGh9V/mU15xIolDQKBgQCk
edh/fO/iplxtj68FL2tvMUFda68FsFoIUm6Db5fttth75KVDTyIGYIICkTDB0MKL
L0IxxzPm4i6ZnR96IscHIj9WZFLIgUo+Ec7wOA/k5lmpmr7S11ZnYb1BHJjfKf9/
vqmarwpseW0LRfD75tJyUeR9hAfxhTgxpHCHjfqmhQKBgBRrk0tiTEm+Tf2djQGv
F6KxVIJ3VZRqY2+u02E/pveIRkcCHHjPqsaNLJEHNX3c0GxHRLAwri2Mnl5fI2Bh
LA/Ch66SwJnz+8hDzY29yHCAWTmVWPgstXMxQYAKLNgfSKc7TL6V2VLM5Hc3qxRn
XydDdn8bDLvKtRDpCgfW6/mg
-----END PRIVATE KEY-----
"""
client_email = "facebook-comment-handler@facebook-scrapper-456519.iam.gserviceaccount.com"
client_id = "110762099942441848318"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/facebook-comment-handler%40facebook-scrapper-456519.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
[api_endpoints]
ocr_url = "https://your-ocr-service.com/api/v1/ocr"
scraper_url = "https://facebook-comment-monitor.onrender.com/get/postid"
